### Authorization by token, part 1. Retrieve and save token.
POST https://ijhttp-examples.jetbrains.com/post
Content-Type: application/json

{
  "token": "my-secret-token"
}

> {% client.global.set("auth_token", response.body.json.token); %}

### Authorization by token, part 2. Use token to authorize.
GET https://ijhttp-examples.jetbrains.com/headers
Authorization: Bearer {{auth_token}}

###